const DISCIPLINAS_TURMA_ANO = {
  // Programação - 10º Ano
  PI01: {
    ano: "10º Ano",
    disciplinas: [
      { disciplina: "Algoritmos", professor: "João Leite", horas: 150 },
      { disciplina: "Fundamentos C/C++", professor: "Rui Silva", horas: 100 },
      { disciplina: "Visual Basic", professor: "João Leite", horas: 30 },
      { disciplina: "TIC", professor: "Rui Silva", horas: 25 },
      { disciplina: "Matemática", professor: "Sónia Pinto", horas: 100 },
      { disciplina: "Português", professor: "Natália Cardoso", horas: 80 },
      { disciplina: "Inglês", professor: "Ana Teixeira", horas: 60 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 50 },
    ],
  },
  PI02: {
    ano: "10º Ano",
    disciplinas: [
      { disciplina: "Algoritmos", professor: "João Leite", horas: 150 },
      { disciplina: "Fundamentos C/C++", professor: "Rui Silva", horas: 100 },
      { disciplina: "Visual Basic", professor: "João Leite", horas: 30 },
      { disciplina: "TIC", professor: "Rui Silva", horas: 25 },
      { disciplina: "Matemática", professor: "Sónia Pinto", horas: 100 },
      { disciplina: "Português", professor: "Natália Cardoso", horas: 80 },
      { disciplina: "Inglês", professor: "Ana Teixeira", horas: 60 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 50 },
    ],
  },
  
  // Informática de Gestão - 11º Ano
  IG01: {
    ano: "11º Ano",
    disciplinas: [
      { disciplina: "C / C++ Avançado", professor: "Rui Silva", horas: 170 },
      { disciplina: "C# Avançado", professor: "Rui Silva", horas: 110 },
      { disciplina: "Estrutura de Dados", professor: "Rui Silva", horas: 50 },
      { disciplina: "Desenvolvimento de Aplicações Web", professor: "Telmo Baldaia", horas: 180 },
      { disciplina: "Matemática", professor: "Sónia Pinto", horas: 90 },
      { disciplina: "Português", professor: "Natália Cardoso", horas: 70 },
      { disciplina: "Inglês", professor: "Ana Teixeira", horas: 60 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 50 },
      { disciplina: "Estágio Formativo", professor: "Rui Silva", horas: 240 },
    ],
  },
  IG02: {
    ano: "11º Ano",
    disciplinas: [
      { disciplina: "C / C++ Avançado", professor: "Rui Silva", horas: 170 },
      { disciplina: "C# Avançado", professor: "Rui Silva", horas: 110 },
      { disciplina: "Estrutura de Dados", professor: "Rui Silva", horas: 50 },
      { disciplina: "Desenvolvimento de Aplicações Web", professor: "Telmo Baldaia", horas: 180 },
      { disciplina: "Matemática", professor: "Sónia Pinto", horas: 90 },
      { disciplina: "Português", professor: "Natália Cardoso", horas: 70 },
      { disciplina: "Inglês", professor: "Ana Teixeira", horas: 60 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 50 },
      { disciplina: "Estágio Formativo", professor: "Rui Silva", horas: 240 },
    ],
  },
  
  // Cabeleireira - 12º Ano
  CC03: {
    ano: "12º Ano",
    disciplinas: [
      { disciplina: "Cortes de Cabelo - Principios", professor: "Ana Costa", horas: 120 },
      { disciplina: "Cortes de Cabelo - Tecnicas", professor: "Ana Costa", horas: 150 },
      { disciplina: "Postiço - Aplicação e Manutenção", professor: "Ana Costa", horas: 80 },
      { disciplina: "Tecnicas de Cortes de Cabelo Feminino", professor: "Catia", horas: 140 },
      { disciplina: "Extensões e Alongamento do Cabelo", professor: "Catia", horas: 100 },
      { disciplina: "Tecnicas de Cortes de Cabelo Masculino", professor: "Madalena", horas: 130 },
      { disciplina: "Cuidados Especificos com a Barba e Bigode", professor: "Madalena", horas: 90 },
      { disciplina: "Tecnicas de Design e Corte de Barba e Bigode", professor: "Madalena", horas: 110 },
      { disciplina: "Português", professor: "Rafaela Leite", horas: 60 },
      { disciplina: "Inglês", professor: "Alexandra Cristina", horas: 50 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 40 },
      { disciplina: "Física e Química", professor: "Carmen", horas: 70 },
      { disciplina: "Estágio Formativo", professor: "Manuela Monteiro", horas: 300 },
      { disciplina: "Prova de Aptidão Profissional", professor: "Manuela Monteiro", horas: 50 },
    ],
  },
  CC04: {
    ano: "12º Ano",
    disciplinas: [
      { disciplina: "Cortes de Cabelo - Principios", professor: "Ana Costa", horas: 120 },
      { disciplina: "Cortes de Cabelo - Tecnicas", professor: "Ana Costa", horas: 150 },
      { disciplina: "Postiço - Aplicação e Manutenção", professor: "Ana Costa", horas: 80 },
      { disciplina: "Tecnicas de Cortes de Cabelo Feminino", professor: "Catia", horas: 140 },
      { disciplina: "Extensões e Alongamento do Cabelo", professor: "Catia", horas: 100 },
      { disciplina: "Tecnicas de Cortes de Cabelo Masculino", professor: "Madalena", horas: 130 },
      { disciplina: "Cuidados Especificos com a Barba e Bigode", professor: "Madalena", horas: 90 },
      { disciplina: "Tecnicas de Design e Corte de Barba e Bigode", professor: "Madalena", horas: 110 },
      { disciplina: "Português", professor: "Rafaela Leite", horas: 60 },
      { disciplina: "Inglês", professor: "Alexandra Cristina", horas: 50 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 40 },
      { disciplina: "Física e Química", professor: "Carmen", horas: 70 },
      { disciplina: "Estágio Formativo", professor: "Manuela Monteiro", horas: 300 },
      { disciplina: "Prova de Aptidão Profissional", professor: "Manuela Monteiro", horas: 50 },
    ],
  },
  CC05: {
    ano: "12º Ano",
    disciplinas: [
      { disciplina: "Cortes de Cabelo - Principios", professor: "Ana Costa", horas: 120 },
      { disciplina: "Cortes de Cabelo - Tecnicas", professor: "Ana Costa", horas: 150 },
      { disciplina: "Postiço - Aplicação e Manutenção", professor: "Ana Costa", horas: 80 },
      { disciplina: "Tecnicas de Cortes de Cabelo Feminino", professor: "Catia", horas: 140 },
      { disciplina: "Extensões e Alongamento do Cabelo", professor: "Catia", horas: 100 },
      { disciplina: "Tecnicas de Cortes de Cabelo Masculino", professor: "Madalena", horas: 130 },
      { disciplina: "Cuidados Especificos com a Barba e Bigode", professor: "Madalena", horas: 90 },
      { disciplina: "Tecnicas de Design e Corte de Barba e Bigode", professor: "Madalena", horas: 110 },
      { disciplina: "Português", professor: "Rafaela Leite", horas: 60 },
      { disciplina: "Inglês", professor: "Alexandra Cristina", horas: 50 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 40 },
      { disciplina: "Física e Química", professor: "Carmen", horas: 70 },
      { disciplina: "Estágio Formativo", professor: "Manuela Monteiro", horas: 300 },
      { disciplina: "Prova de Aptidão Profissional", professor: "Manuela Monteiro", horas: 50 },
    ],
  },
  
  // Termalismo - 12º Ano
  TE12: {
    ano: "12º Ano",
    disciplinas: [
      { disciplina: "Termalismo e Hidroginástica", professor: "Andreza", horas: 200 },
      { disciplina: "Área de Integração", professor: "Guilherme", horas: 80 },
      { disciplina: "Português", professor: "Rafaela Leite", horas: 60 },
      { disciplina: "Inglês", professor: "Alexandra Cristina", horas: 50 },
      { disciplina: "Matemática", professor: "Sónia Pinto", horas: 70 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 40 },
      { disciplina: "Física e Química", professor: "Carmen", horas: 70 },
      { disciplina: "Física e Química", professor: "Vera Rafaela", horas: 70 },
      { disciplina: "Estágio Formativo", professor: "Guilherme", horas: 300 },
      { disciplina: "Prova de Aptidão Profissional", professor: "Guilherme", horas: 50 },
    ],
  },
  TE13: {
    ano: "12º Ano",
    disciplinas: [
      { disciplina: "Termalismo e Hidroginástica", professor: "Andreza", horas: 200 },
      { disciplina: "Área de Integração", professor: "Guilherme", horas: 80 },
      { disciplina: "Português", professor: "Rafaela Leite", horas: 60 },
      { disciplina: "Inglês", professor: "Alexandra Cristina", horas: 50 },
      { disciplina: "Matemática", professor: "Sónia Pinto", horas: 70 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 40 },
      { disciplina: "Física e Química", professor: "Carmen", horas: 70 },
      { disciplina: "Física e Química", professor: "Vera Rafaela", horas: 70 },
      { disciplina: "Estágio Formativo", professor: "Guilherme", horas: 300 },
      { disciplina: "Prova de Aptidão Profissional", professor: "Guilherme", horas: 50 },
    ],
  },
  TE14: {
    ano: "12º Ano",
    disciplinas: [
      { disciplina: "Termalismo e Hidroginástica", professor: "Andreza", horas: 200 },
      { disciplina: "Área de Integração", professor: "Guilherme", horas: 80 },
      { disciplina: "Português", professor: "Rafaela Leite", horas: 60 },
      { disciplina: "Inglês", professor: "Alexandra Cristina", horas: 50 },
      { disciplina: "Matemática", professor: "Sónia Pinto", horas: 70 },
      { disciplina: "Educação Física", professor: "Ricardo Silveira", horas: 40 },
      { disciplina: "Física e Química", professor: "Carmen", horas: 70 },
      { disciplina: "Física e Química", professor: "Vera Rafaela", horas: 70 },
      { disciplina: "Estágio Formativo", professor: "Guilherme", horas: 300 },
      { disciplina: "Prova de Aptidão Profissional", professor: "Guilherme", horas: 50 },
    ],
  },
};

export default DISCIPLINAS_TURMA_ANO;